"""initial schema

Revision ID: 38e972dbd6e1
Revises: 
Create Date: 2026-03-12 13:37:49.580225

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision = '38e972dbd6e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('disabled', sa.Boolean(), nullable=False),
        sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=False),
        sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
